#!/bin/bash

find /sys/fs/cgroup/ -name cgroup.freeze | while read -r file
do
	value=$(cat $file)
	[[ "$value" != "1" ]] && continue

	dirname=$(dirname $file)
	name=$(basename $dirname)
	echo "$name"
done | sort
